### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by MSinnott** [teamursamajor/2018-Robot-Code---2849#6]
We need to stablize the drivetrain for auto (and also teleop, at least a bit). This coudl be a static power differential, a PID style closed loop control, or maybe a closed loop heading correction in the drive task. Thoughts?

**Comment by teamursamajor** [comment]
idk what static power differential is, but PID closed loop control and closed loop heading correction would both sound good to me. Charlie expressed concerns about PIDs sometimes being wonky, as in they run the risk of oscillating back and forth, but we can address that issue with some checks/fixes. If you have any knowledge about the pros/cons for each of these options, that would help. -20XX

**Comment by MSinnott** [comment]
So static power differentiial is what we did w/the rightAdjust (and its kinda sucky). Also, velocity PIDs wont have issues oscillating because you have to PID on velocity differentials, not the velocity itself, but they do have issues with response time / latency (thats why you want to use a feedforward term).

**Comment by MSinnott** [comment]
Yeah, so this is kinda sorta done - I mean there are some things that we still need to work on but it's pretty much good
